### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by LoveMiki** [loadder/Dynamic-Meta-filter#3]
Thanks for sharing the codes and the excellent work.

I noticed that you used a batch size of 4 in training procedure, could you tell me how much GPU memory is required to process such a large training set?

**Comment by chmxu** [comment]
I used one 32G V100 in my experiment and I remember the model do not drain the GPU memory. Hope this is helpful.

**Comment by LoveMiki** [comment]
> drain

Thank you so much!

**Comment by LoveMiki** [comment]
> I used one 32G V100 in my experiment and I remember the model do not drain the GPU memory. Hope this is helpful.

Oh, sorry to bother you again. Could u share the link of tieredImageNet dataset used in the experiments? Thank you advance.

**Comment by chmxu** [comment]
You can check [MTL](https://github.com/yaoyao-liu/meta-transfer-learning) for the download link of tieredImageNet.
