### ISSUE TITLE
ImportError: cannot import name '_C' from 'dconv'

### ISSUE THREAD

**Issue by LoveMiki** [loadder/Dynamic-Meta-filter#4]
Dear authors, I am trying to re-implement the code, but I get this error. 
Are there any solutions? I have followed the requirements to install the right version of packages.

**Comment by chmxu** [comment]
Hi,
I guess you haven't compile the dconv module. You need to run the following script.
`python setup.py develop build`
Hope this can help you with your problem.

**Comment by LoveMiki** [comment]
> Hi, I guess you haven't compile the dconv module. You need to run the following script. `python setup.py develop build` Hope this can help you with your problem.

Thank you very much!!! It my fault that i didn't see this command line. Now i can successfully run the code.

**Comment by LoveMiki** [comment]
Oh, by the way, did you experiment with the pickle files of miniImageNet, just like CAN?

**Comment by chmxu** [comment]
> Oh, by the way, did you experiment with the pickle files of miniImageNet, just like CAN?

No, we only use the image files to conduct our experiments.
